---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherforecast
spec:
  selector:
    matchLabels:
      app: weatherforecast
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: weatherforecast
    spec:
      containers:
      - name: weatherforecast #+ GUID
        image: lennartacr.azurecr.io/weatherforecast:#{Build.BuildId}#
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: weatherforecast
spec:
  ports:
  - name: http-port
    port: 80
  - name: https-port
    port: 443
  selector:
    app: weatherforecast
  type: LoadBalancer
